class Field:
    username_textfield = "//input[@id='user-name']"
    username_passwordfield = "//input[@id='password']"
    login_button = "//input[@id='login-button']"
    product_span = "//span[@class='title']"
    add_first_to_card = "//*[@id='add-to-cart-sauce-labs-backpack']"
    add_second_to_card = "//*[@id='add-to-cart-sauce-labs-bolt-t-shirt']"
    add_third_to_card = "//*[@id='add-to-cart-sauce-labs-onesie']"
    dropdown = "//*[@id='header_container']/div[2]/div[2]/span/select"
    high_to_low = "//*[@id='header_container']/div[2]/div[2]/span/select/option[4]"
    card = "//*[@id='shopping_cart_container']/a"
    checkout = "//*[@id='checkout']"
    first_name = "//*[@id='first-name']"
    last_name = "//*[@id='last-name']"
    postal_code = "//*[@id='postal-code']"
    cont_page = "//*[@id='continue']"
    items = "//div[@class='summary_subtotal_label']"
    total = "//div[@class='summary_total_label']"
    get_tax = "//div[@class='summary_tax_label']"

"""
#item_total = "//*[@id='checkout_summary_container']/div/div[2]/div[5]/text()[2]"
#item_total = "//div[@class='summary_subtotal_label'][contains(text()='53.97']"
"""

